name: 'Trigger Deploy'
description: 'Can either trigger a deployment to a specific environment / namespace, or trigger a number of deployments based on the event which triggered it.'
author: 'switcher.ie'
inputs:
  app:
    description: 'The application to deploy; the repository slug.'
  environment:
    description: 'The environment to deploy to. Either "staging" or "production".'
  namespace:
    description: 'The namespace to deploy to. Only valid if `environment` is "staging".'
  ref:
    description: 'The commit reference to deploy.'
  github_access_token:
    description: 'A GitHub Personal Access Token with `repo`'
    required: true
outputs:
  deployment:
    description: 'first deployment as JSON-encoded object'
  deployments:
    description: 'JSON-encoded array of GitHub deployments'
runs:
  using: 'node12'
  main: 'dist/index.js'
